root = "/var/vcap/store/containerd"
state = "/var/vcap/data/containerd/state"
no_subreaper = false
oom_score = 0

[grpc]
  address = "/var/vcap/sys/run/containerd/containerd.sock"
  uid = 4294967294
  gid = 4294967294

[debug]
  address = "/var/vcap/sys/run/containerd/debug.sock"
  uid = 4294967294
  gid = 4294967294
  level = "info"

[metrics]
  address = ""

[cgroup]
  path = ""
