- type: replace
  path: /releases/-
  value:
    name: bpm
    version: create
    url: file:///Users/pivotal/workspace/bpm-release

- type: replace
  path: /instance_groups/name=garden/jobs/-
  value:
    name: bpm
    release: bpm
